CREATE TABLE movie (
  id int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  title varchar(100) NOT NULL,
  year char(4) NOT NULL,
  genre varchar(20) NOT NULL,
  image text NOT NULL,
  synopsis text
)AUTO_INCREMENT=1;

INSERT INTO `movie` (`id`, `title`, `year`, `genre`, `image`, `synopsis`) VALUES
(1, 'Black Panther', '2018', 'superhero', 'https://kennedytorch.org/wp-content/uploads/2018/02/black-panther-image.jpg', 'After the death of his father, T\'Challa returns home to the African nation of Wakanda to take his rightful place as king. When a powerful enemy suddenly reappears, T\'Challa\'s mettle as king -- and as Black Panther -- gets tested when he\'s drawn into a conflict that puts the fate of Wakanda and the entire world at risk. Faced with treachery and danger, the young king must rally his allies and release the full power of Black Panther to defeat his foes and secure the safety of his people.'),
(9, 'Lara Croft: Tomb Raider', '2001', 'action', 'http://www.gstatic.com/tv/thumb/movieposters/27735/p27735_p_v8_ah.jpg', 'This live action feature is inspired by the most successful interactive video-game character in history -- Lara Croft. Beautiful and brainy, Lara (Angelina Jolie) is the heroine of Eidos Interactive\'s phenomenally successful \"Tomb Raider\" game series. It is one woman\'s fearless quest criss-crossing the globe, in an amazing attempt to save the world.'),
(10, 'Harry Potter and the Philosopher\'s Stone', '2001', 'fantasy', 'http://t0.gstatic.com/images?q=tbn:ANd9GcT_9nrOnN8sYfZZHJ06EIBSoEO5qjx7uHHEs6VtKNplGVuGhZuC', 'Adaptation of the first of J.K. Rowling\'s popular children\'s novels about Harry Potter, a boy who learns on his eleventh birthday that he is the orphaned son of two powerful wizards and possesses unique magical powers of his own. He is summoned from his life as an unwanted child to become a student at Hogwarts, an English boarding school for wizards. There, he meets several friends who become his closest allies and help him discover the truth about his parents\' mysterious deaths.'),
(11, 'Harry Potter and the Chamber of Secrets', '2002', 'fantasy', 'http://t0.gstatic.com/images?q=tbn:ANd9GcTltzcooPkGcy1fKKqzSuO8U6S9XBpNDR9MuYc9SS_L5AbAn66O', 'The follow-up to \"Harry Potter and the Sorcerer\'s Stone\" finds young wizard Harry Potter (Daniel Radcliffe) and his friends, Ron (Rupert Grint) and Hermione (Emma Watson), facing new challenges during their second year at Hogwarts School of Witchcraft and Wizardry as they try to discover a dark force that is terrorizing the school.'),
(12, 'Harry Potter and the Prisoner of Azkaban', '2004', 'fantasy', 'http://t3.gstatic.com/images?q=tbn:ANd9GcSkFf3MN_oao6q3gysHpVfJA2lICz2ckgXE2VoKRWEGk0huoKnQ', 'Harry Potter\'s (Daniel Radcliffe) third year at Hogwarts starts off badly when he learns deranged killer Sirius Black (Gary Oldman) has escaped from Azkaban prison and is bent on murdering the teenage wizard. While Hermione\'s (Emma Watson) cat torments Ron\'s (Rupert Grint) sickly rat, causing a rift among the trio, a swarm of nasty Dementors is sent to protect the school from Black. A mysterious new teacher helps Harry learn to defend himself, but what is his secret tie to Sirius Black?'),
(13, 'The Avengers', '2012', 'superhero', 'http://t1.gstatic.com/images?q=tbn:ANd9GcTp0qlAoWcOOswIkL_qpjYzJqCCDmWXiBzCXiqbE43Obo8c0Z-s', 'When Thor\'s evil brother, Loki (Tom Hiddleston), gains access to the unlimited power of the energy cube called the Tesseract, Nick Fury (Samuel L. Jackson), director of S.H.I.E.L.D., initiates a superhero recruitment effort to defeat the unprecedented threat to Earth. Joining Fury\'s \"dream team\" are Iron Man (Robert Downey Jr.), Captain America (Chris Evans), the Hulk (Mark Ruffalo), Thor (Chris Hemsworth), the Black Widow (Scarlett Johansson) and Hawkeye (Jeremy Renner).'),
(14, 'Shaun of the Dead', '2014', 'comedy', 'http://t2.gstatic.com/images?q=tbn:ANd9GcRK-absH_f7E-Hp0-lnlKdvhv9mzi7AzGVXh5L7dfcq1fAKmr7I', 'Shaun (Simon Pegg) is a 30-something loser with a dull, easy existence. When he\'s not working at the electronics store, he lives with his slovenly best friend, Ed (Nick Frost), in a small flat on the outskirts of London. The only unpredictable element in his life is his girlfriend, Liz (Kate Ashfield), who wishes desperately for Shaun to grow up and be a man. When the town is inexplicably overrun with zombies, Shaun must rise to the occasion and protect both Liz and his mother (Penelope Wilton).'),
(15, 'The Grand Budapest Hotel', '2014', 'comedy', 'http://t0.gstatic.com/images?q=tbn:ANd9GcSDDmHpt0TcHkK9DCv0QU-Xx4WNEVOJnHlj7pVfN61-1mEX2eCG', 'n the 1930s, the Grand Budapest Hotel is a popular European ski resort, presided over by concierge Gustave H. (Ralph Fiennes). Zero, a junior lobby boy, becomes Gustave\'s friend and protege. Gustave prides himself on providing first-class service to the hotel\'s guests, including satisfying the sexual needs of the many elderly women who stay there. When one of Gustave\'s lovers dies mysteriously, Gustave finds himself the recipient of a priceless painting and the chief suspect in her murder.'),
(8, 'Tomb Raider', '2018', 'action', 'http://t1.gstatic.com/images?q=tbn:ANd9GcQGBx-FI1Xp1Xk9raKVhCrW2pj-vBUpbjfY5liEfDmU2DzKV-Uf', 'Lara Croft is the fiercely independent daughter of an eccentric adventurer who vanished years earlier. Hoping to solve the mystery of her father\'s disappearance, Croft embarks on a perilous journey to his last-known destination -- a fabled tomb on a mythical island that might be somewhere off the coast of Japan. The stakes couldn\'t be higher as Lara must rely on her sharp mind, blind faith and stubborn spirit to venture into the unknown.');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
